<billTo>
    @if($billTo->firstName)
    <firstName>{{$billTo->firstName}}</firstName>
    @endif
    @if($billTo->lastName)
    <lastName>{{$billTo->lastName}}</lastName>
    @endif
    @if($billTo->company)
    <company>{{$billTo->company}}</company>
    @endif
    @if($billTo->address)
    <address>{{$billTo->address}}</address>
    @endif
    @if($billTo->city)
    <city>{{$billTo->city}}</city>
    @endif
    @if($billTo->state)
    <state>{{$billTo->state}}</state>
    @endif
    @if($billTo->zip)
    <zip>{{$billTo->zip}}</zip>
    @endif
    @if($billTo->phoneNumber)
    <phoneNumber>{{$billTo->phoneNumber}}</phoneNumber>
    @endif
</billTo>
