<?xml version='1.0' encoding='utf-8'?>
<createCustomerProfileRequest xmlns='AnetApi/xml/v1/schema/AnetApiSchema.xsd'>
    <merchantAuthentication>
        <name>{{$credentials['api_name']}}</name>
        <transactionKey>{{$credentials['api_key']}}</transactionKey>
    </merchantAuthentication>
    <profile>
        <merchantCustomerId>{{$profile['merchant_customer_id']}}</merchantCustomerId>
        @if(isset($profile['description']))
        <description>{{$profile['description']}}</description>
        @endif
        @if(isset($profile['email']))
        <email>{{$profile['email']}}</email>
        @endif
        @if(isset($profile['payment_profiles']))
        <paymentProfiles>
            <customerType>business</customerType>
            <billTo>
                <firstName>{{$user->fname}}</firstName>
                <lastName>{{$user->lname}}</lastName>
                <company>{{$data['ccName']}}</company>
                <address>{{$data['ccStreet']}}</address>
                <city>{{$data['ccCity']}}</city>
                <state>{{$data['ccState']}}</state>
                <zip>{{$data['ccZip']}}</zip>
                <phoneNumber>{{$data['ccPhone']}}</phoneNumber>
            </billTo>
            <payment>
                <creditCard>
                    <cardNumber>{{$data['ccNumber']}}</cardNumber>
                    <expirationDate>
                        {{$data['ccYear']}}-{{$data['ccMonth']}}
                    </expirationDate>
                </creditCard>
            </payment>
        </paymentProfiles>
        @endif
    </profile>
    <validationMode>liveMode</validationMode>
</createCustomerProfileRequest>
